# frozen_string_literal: true

# Generated by squeeze's release workflow; do not edit.
class Squeeze < Formula
  desc "Extract URLs, emails, IPs, hashes, TODOs, and more from any text"
  homepage "https://github.com/aymericbeaumet/squeeze"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/aymericbeaumet/squeeze/releases/download/v0.4.0/squeeze-v0.4.0-macos-arm64.tar.gz"
      sha256 "a5f68498e1c73162a52e8fbd32392ca1bdcabbfcb37550b23bb4f4e81868e336"
    end
    on_intel do
      url "https://github.com/aymericbeaumet/squeeze/releases/download/v0.4.0/squeeze-v0.4.0-macos-amd64.tar.gz"
      sha256 "a79c05527adf1df3ce96dde250a60c7dd6f97af7df12bc97916c77c486f2eb2d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aymericbeaumet/squeeze/releases/download/v0.4.0/squeeze-v0.4.0-linux-arm64.tar.gz"
      sha256 "d6116d9a52b1d8a8fee40a267c1427019a69358a3660ecc65fa4ecb8da7b23bc"
    end
    on_intel do
      url "https://github.com/aymericbeaumet/squeeze/releases/download/v0.4.0/squeeze-v0.4.0-linux-amd64.tar.gz"
      sha256 "07efb406798ce4f5bd581a3b78f9c7ba061300e243d3a5aa08213d64603dd81c"
    end
  end

  conflicts_with "squeeze-nightly", because: "squeeze-nightly and squeeze install the same binary"

  def install
    bin.install "squeeze"
    generate_completions_from_executable(bin/"squeeze", "--completions")
  end

  test do
    output = pipe_output("#{bin}/squeeze --url", "visit https://example.com today")
    assert_equal "https://example.com", output.strip
  end
end
