# frozen_string_literal: true

# Generated by squeeze's release workflow; do not edit.
class Squeeze < Formula
  desc "Extract URLs, emails, IPs, hashes, TODOs, and more from any text"
  homepage "https://github.com/aymericbeaumet/squeeze"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/aymericbeaumet/squeeze/releases/download/v0.5.0/squeeze-v0.5.0-macos-arm64.tar.gz"
      sha256 "958e56b4f716dbffa735714d2d43f29109e47284da40285e37430dc602f88f01"
    end
    on_intel do
      url "https://github.com/aymericbeaumet/squeeze/releases/download/v0.5.0/squeeze-v0.5.0-macos-amd64.tar.gz"
      sha256 "33119005570bde2a2250f5b9e3038c394a3307261c706902ad430044a1ec3e68"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aymericbeaumet/squeeze/releases/download/v0.5.0/squeeze-v0.5.0-linux-arm64.tar.gz"
      sha256 "a2e1de00915d4ca01393dfac45dab544896369f4877cc1efc12eccd95ae3bd30"
    end
    on_intel do
      url "https://github.com/aymericbeaumet/squeeze/releases/download/v0.5.0/squeeze-v0.5.0-linux-amd64.tar.gz"
      sha256 "adbc2d110b842021fc48f3d35d8837398503009b78f5ac02b3566570dad9542c"
    end
  end

  conflicts_with "squeeze-nightly", because: "squeeze-nightly and squeeze install the same binary"

  def install
    bin.install "squeeze"
    generate_completions_from_executable(bin/"squeeze", "--completions")
  end

  test do
    output = pipe_output("#{bin}/squeeze --url", "visit https://example.com today")
    assert_equal "https://example.com", output.strip
  end
end
